included:
  - PixelFlow
  - PixelFlowTests

excluded:
  - PixelFlow.xcodeproj
  - PixelFlow.xcworkspace
  - PixelFlow/Engine/Shaders
  - PixelFlow/Resources

disabled_rules:
  - trailing_whitespace
  - line_length
  - type_body_length
  - file_length
  - function_body_length
  - cyclomatic_complexity

opt_in_rules:
  - force_unwrapping

force_unwrapping:
  severity: error